# Generated by Django 2.2.1 on 2019-05-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190514_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='basket_free',
            field=models.BooleanField(default=True),
        ),
    ]
